version: "3"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: pedrohpsarmento/nginx
    container_name: nginx
    networks:
      - local
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./nginx:/etc/nginx/conf.d
    command: /bin/sh -c "exec nginx -g 'daemon off;'"

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: pedrohpsarmento/node
    container_name: app
    networks:
      - local
    volumes:
      - ./node:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
    tty: true
    command: /bin/sh -c "npm install && node index.js"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - local
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 10s
      retries: 3


networks:
  local:
    driver: bridge